### ISSUE TITLE
Result View Quiz

### ISSUE THREAD

**Issue by achmaddwiprasetyo** [opensource-edukasi/lms-quiz-services#7]
- Get Result Quiz by QuizId and student_id

**Comment by Ferrykun07** [comment]
package main

import (
	"fmt"
)

type Question struct {
	Text         string
	UserAnswer   string
	CorrectAnswer string
}

func main() {
	score := 8 // Skor kuis

	questions := []Question{
		{
			Text:         "Pertanyaan 1",
			UserAnswer:   "Jawaban pengguna 1",
			CorrectAnswer: "Jawaban yang benar 1",
		},
		{
			Text:         "Pertanyaan 2",
			UserAnswer:   "Jawaban pengguna 2",
			CorrectAnswer: "Jawaban yang benar 2",
		},
	}

	fmt.Println("Hasil Quiz")
	fmt.Printf("Skor: %d\n", score)
	fmt.Println("Jawaban Anda:")

	for _, q := range questions {
		fmt.Println(q.Text)
		if q.UserAnswer == q.CorrectAnswer {
			fmt.Println("Jawaban Anda: Benar")
		} else {
			fmt.Println("Jawaban Anda: Salah")
		}
	}

	fmt.Println("Terima kasih telah mengikuti kuis!")
}
